// Generated by IcedCoffeeScript 108.0.13
(function() {
  var reserved_hash;

  reserved_hash = {
    "get_force": true,
    "get_chain_id": true,
    "transaction": true,
    "get_contract": true,
    "get_entrypoint": true,
    "size": true,
    "int": true,
    "abs": true,
    "is_nat": true,
    "amount": true,
    "balance": true,
    "now": true,
    "unit": true,
    "source": true,
    "sender": true,
    "failwith": true,
    "bitwise_or": true,
    "bitwise_and": true,
    "bitwise_xor": true,
    "string_concat": true,
    "string_slice": true,
    "crypto_check": true,
    "crypto_hash_key": true,
    "bytes_concat": true,
    "bytes_slice": true,
    "bytes_pack": true,
    "bytes_unpack": true,
    "set_empty": true,
    "set_mem": true,
    "set_add": true,
    "set_remove": true,
    "set_iter": true,
    "set_fold": true,
    "list_iter": true,
    "list_fold": true,
    "list_map": true,
    "map_iter": true,
    "map_map": true,
    "map_fold": true,
    "map_remove": true,
    "map_update": true,
    "map_get": true,
    "map_mem": true,
    "sha_256": true,
    "sha_512": true,
    "blake2b": true,
    "cons": true,
    "EQ": true,
    "NEQ": true,
    "NEG": true,
    "ADD": true,
    "SUB": true,
    "TIMES": true,
    "DIV": true,
    "MOD": true,
    "NOT": true,
    "AND": true,
    "OR": true,
    "GT": true,
    "GE": true,
    "LT": true,
    "LE": true,
    "CONS": true,
    "address": true,
    "self_address": true,
    "implicit_account": true,
    "set_delegate": true,
    "to": true,
    "args": true,
    "main": true,
    "map": true,
    "some": true
  };

  reserved_hash[config.contract_storage] = true;

  reserved_hash[config.op_list] = true;

  this.translate_var_name = function(name, ctx) {
    if (name[0] === "_") {
      name = ("" + config.fix_underscore + "_") + name;
    }
    name = name.substr(0, 1).toLowerCase() + name.substr(1);
    if (name === "@main") {
      return "main";
    } else if (reserved_hash.hasOwnProperty(name)) {
      return "" + config.reserved + "__" + name;
    } else {
      return name;
    }
  };

}).call(window.translate_var_name = {});
