config = require "../src/config"
config.fix_underscore = "test_fix_underscore"
config.reserved       = "test_reserved_long_"
config.initialized    = "#{config.reserved}__initialized"
config.empty_state    = "#{config.reserved}__empty_state"
